# Generated by Django 5.2.7 on 2025-11-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alers", "0003_studentprofile_profilechatsession_profilemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="learning_progress",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
